
import React, { useState } from 'react';
import { SettingsIcon, ChevronLeftIcon, ChevronRightIcon } from '../components/Icons';

type SettingsView = 'menu' | 'about' | 'terms';

const SettingsPage: React.FC = () => {
    const [view, setView] = useState<SettingsView>('menu');

    const renderContent = () => {
        switch (view) {
            case 'about':
                return (
                    <div>
                        <button onClick={() => setView('menu')} className="flex items-center text-sm text-brand-primary mb-4">
                            <ChevronLeftIcon className="w-5 h-5" />
                            <span>Back to Settings</span>
                        </button>
                        <h3 className="text-2xl font-bold text-brand-dark mb-4">About Creativ AI</h3>
                        <div className="space-y-4 text-brand-gray">
                            <p>Creativ AI is your all-in-one platform for exploring the creative power of artificial intelligence. Our application provides a suite of tools that leverage the cutting-edge Google Gemini API to bring your ideas to life.</p>
                            <p>Whether you're engaging in intelligent conversations with our AI Chat, generating stunning visuals with the Image Generator, or composing unique song ideas, Creativ AI is designed to be your ultimate creative companion.</p>
                            <p>Our mission is to make advanced AI accessible and intuitive, empowering creators, developers, and enthusiasts to push the boundaries of imagination.</p>
                            <p>Version: 1.0.0</p>
                        </div>
                    </div>
                );
            case 'terms':
                return (
                    <div>
                        <button onClick={() => setView('menu')} className="flex items-center text-sm text-brand-primary mb-4">
                            <ChevronLeftIcon className="w-5 h-5" />
                            <span>Back to Settings</span>
                        </button>
                        <h3 className="text-2xl font-bold text-brand-dark mb-4">Terms of Service</h3>
                        <div className="space-y-4 text-brand-gray text-sm">
                            <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>
                            <p>By downloading or using Creativ AI, you agree to these terms. Please read them carefully.</p>
                            <p><strong>1. Use of the App:</strong> You agree to use Creativ AI only for lawful purposes. You are responsible for any content you generate and your communications with others while using our services.</p>
                            <p><strong>2. App Store Terms:</strong> If you downloaded this app from the Apple App Store or Google Play Store, you also agree to their respective terms of service. Your license to use Creativ AI is granted under the terms of the applicable app store's Licensed Application End User License Agreement (EULA).</p>
                            <p><strong>3. Content:</strong> The content you generate with Creativ AI ("Generated Content") is your own. We do not claim any ownership rights in the text, images, or other content you create. However, by using the app, you grant us a license to use, reproduce, and display the Generated Content solely for the purpose of operating and improving the service.</p>
                            <p><strong>4. Prohibited Conduct:</strong> You agree not to use the app to generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable.</p>
                            <p><strong>5. Disclaimers:</strong> The services are provided "as is." We make no warranties, express or implied, regarding the accuracy, reliability, or availability of the service. The AI-generated content may sometimes be inaccurate or offensive; we are not responsible for the content generated by the AI models.</p>
                            <p><strong>6. Changes to Terms:</strong> We may modify these terms at any time. We will notify you of any changes by posting the new Terms of Service in the app. You are advised to review this page periodically for any changes.</p>
                        </div>
                    </div>
                );
            case 'menu':
            default:
                return (
                     <div>
                        <button
                            onClick={() => setView('about')}
                            className="w-full flex justify-between items-center text-left p-4 bg-brand-light hover:bg-brand-light-gray rounded-lg transition-colors border border-brand-light-gray"
                        >
                            <div>
                                <h4 className="font-semibold text-brand-dark">About</h4>
                                <p className="text-sm text-brand-gray">Learn more about the app and its version.</p>
                            </div>
                            <ChevronRightIcon />
                        </button>
                        <button
                            onClick={() => setView('terms')}
                            className="w-full flex justify-between items-center text-left p-4 bg-brand-light hover:bg-brand-light-gray rounded-lg transition-colors mt-4 border border-brand-light-gray"
                        >
                            <div>
                                <h4 className="font-semibold text-brand-dark">Terms of Service</h4>
                                <p className="text-sm text-brand-gray">Read our terms and conditions.</p>
                            </div>
                            <ChevronRightIcon />
                        </button>
                    </div>
                );
        }
    }

    return (
        <div className="flex flex-col h-full bg-white rounded-2xl shadow-lg overflow-hidden border border-brand-light-gray">
            <header className="p-5 bg-brand-light border-b border-brand-light-gray">
                <h2 className="text-xl font-bold text-brand-dark flex items-center gap-3">
                    <SettingsIcon />
                    Settings
                </h2>
            </header>
            <div className="p-5">
                {renderContent()}
            </div>
        </div>
    );
};

export default SettingsPage;
